-- CreateTable
CREATE TABLE IF NOT EXISTS "SiteSettings" (
    "id" TEXT NOT NULL DEFAULT 'default',
    "siteName" TEXT NOT NULL DEFAULT 'IZAZOV 9.0',
    "shortName" TEXT NOT NULL DEFAULT 'IZAZOV',
    "tagline" TEXT NOT NULL DEFAULT 'Where Talent Meets Glory',
    "logoUrl" TEXT,
    "faviconUrl" TEXT,
    "primaryColor" TEXT NOT NULL DEFAULT '#931827',
    "backgroundColor" TEXT NOT NULL DEFAULT '#000000',
    "surfaceColor" TEXT NOT NULL DEFAULT '#231F20',
    "cardColor" TEXT NOT NULL DEFAULT '#111011',
    "textColor" TEXT NOT NULL DEFAULT '#FFFFFF',
    "mutedTextColor" TEXT NOT NULL DEFAULT '#B8B8B8',
    "borderColor" TEXT NOT NULL DEFAULT '#2D292A',
    "heroTitle" TEXT NOT NULL DEFAULT 'IGNITE THE ARENA',
    "heroSubtitle" TEXT NOT NULL DEFAULT 'THE 9TH EDITION • MARCH 2026',
    "heroDescription" TEXT NOT NULL DEFAULT 'The flagship campus festival uniting cultural spectacles, 24-hour hackathons, esports battles, literary arenas, and the four-house championship.',
    "heroButtonText" TEXT NOT NULL DEFAULT 'Explore Events',
    "heroButtonLink" TEXT NOT NULL DEFAULT '/events',
    "heroImageUrl" TEXT,
    "showFeaturedEvents" BOOLEAN NOT NULL DEFAULT true,
    "showAnnouncements" BOOLEAN NOT NULL DEFAULT true,
    "showResults" BOOLEAN NOT NULL DEFAULT true,
    "showSchedule" BOOLEAN NOT NULL DEFAULT true,
    "showStats" BOOLEAN NOT NULL DEFAULT true,
    "aboutTitle" TEXT NOT NULL DEFAULT 'About IZAZOV 9.0',
    "aboutDescription" TEXT NOT NULL DEFAULT 'IZAZOV is the premier annual inter-collegiate cultural and technical festival. Over three days, students from across departments and institutions compete in cultural showcases, algorithmic battles, parliamentary debates, and gaming tournaments.',
    "aboutImageUrl" TEXT,
    "contactEmail" TEXT NOT NULL DEFAULT 'fest@izazov9.com',
    "contactPhone" TEXT NOT NULL DEFAULT '+91 98765 43210',
    "contactWhatsApp" TEXT,
    "contactAddress" TEXT NOT NULL DEFAULT 'Main Campus Arena, University City',
    "instagramUrl" TEXT,
    "facebookUrl" TEXT,
    "youtubeUrl" TEXT,
    "whatsappUrl" TEXT,
    "websiteUrl" TEXT,
    "festName" TEXT NOT NULL DEFAULT 'IZAZOV',
    "edition" TEXT NOT NULL DEFAULT '9.0',
    "startDate" TEXT NOT NULL DEFAULT 'MARCH 25, 2026',
    "endDate" TEXT NOT NULL DEFAULT 'MARCH 28, 2026',
    "venueName" TEXT NOT NULL DEFAULT 'Main Campus Arena',
    "venueLocation" TEXT NOT NULL DEFAULT 'Block A & Central Amphitheatre',
    "showEvents" BOOLEAN NOT NULL DEFAULT true,
    "showScheduleNav" BOOLEAN NOT NULL DEFAULT true,
    "showVenuesNav" BOOLEAN NOT NULL DEFAULT true,
    "showAnnouncementsNav" BOOLEAN NOT NULL DEFAULT true,
    "showResultsNav" BOOLEAN NOT NULL DEFAULT true,
    "showAboutNav" BOOLEAN NOT NULL DEFAULT true,
    "footerText" TEXT NOT NULL DEFAULT 'IZAZOV 9.0 is the official campus festival operations and competition management system.',
    "copyrightText" TEXT NOT NULL DEFAULT '© 2026 IZAZOV 9.0 Fest Committee. All rights reserved.',
    "metaTitle" TEXT NOT NULL DEFAULT 'IZAZOV 9.0 — Campus Fest Operations & Management Platform',
    "metaDescription" TEXT NOT NULL DEFAULT 'Official festival management platform for IZAZOV 9.0 — explore competitions, schedules, live results, and official announcements.',
    "ogImageUrl" TEXT,
    "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT "SiteSettings_pkey" PRIMARY KEY ("id")
);
